---
driver_plugin: vagrant

platforms:

- name: ubuntu-14.04
  driver_config:
#    box: chef/ubuntu-14.04
    box: ubuntu/trusty64
    require_chef_omnibus: true
    customize:
      memory:    1024
  run_list:
    - recipe[apt]

- name: ubuntu-12.04
  driver_config:
    box: ubuntu/precise64
    require_chef_omnibus: true
    customize:
      memory:    1024
  run_list:
    - recipe[apt]

- name: centos-7.0
  driver_config:
    box: chef/centos-7.0
    customize:
      memory:    1024
  run_list:
    - recipe[yum]

suites:

- name: default
  run_list: recipe[sbt-extras]

- name: without_optfiles
  run_list: recipe[sbt-extras]
  attributes:
    sbt-extras:
      jvmopts:
        filename: ''  # empty string also means no template to deploy
      sbtopts:
        filename: ~   # '~' is parsed as Null value

- name: openjdk7-customized
  run_list:
    - recipe[java::openjdk]
    - recipe[sbt-extras]
  attributes:
    java:
      jdk_version: '7'
    sbt-extras:
      script_name: rebel_cut
      sbtopts:
        batch:              true
        no-colors:          true
      jvmopts:
        total_memory:       1024
        thread_stack_size:     3
      owner: vagrant
      group: vagrant
      setup_dir: /usr/bin
      user_setup:
        vagrant:
          sbt:    ['0.13.6', '0.12.4', '0.11.3']
          scala:  ['2.11.4', '2.10.4', '2.9.3']
