---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: latest

platforms:

- name: ubuntu-14.04
  driver:
    customize:
      memory: 1024
  run_list:
    - recipe[apt]

- name: ubuntu-12.04
  driver:
    customize:
      memory: 1024
  run_list:
    - recipe[apt]

- name: centos-7.1
  driver:
    customize:
      memory: 1024
    run_list:
      - recipe[yum]

suites:

- name: default
  run_list: recipe[sbt-extras]

- name: without_optfiles
  run_list: recipe[sbt-extras]
  attributes:
    sbt-extras:
      jvmopts:
        filename: ''  # empty string also means no template to deploy
      sbtopts:
        filename: ~   # '~' is parsed as Null value

- name: openjdk7-customized
  run_list:
    - recipe[java::openjdk]
    - recipe[sbt-extras]
  attributes:
    java:
      jdk_version: '7'
    sbt-extras:
      script_name: rebel_cut
      sbtopts:
        batch:              true
        no-colors:          true
      jvmopts:
        total_memory:       1024
        thread_stack_size:     3
      owner: vagrant
      group: vagrant
      setup_dir: /usr/bin
      user_setup:
        vagrant:
          sbt:    ['0.13.9', '0.12.4']
          scala:  ['2.11.7', '2.10.6', '2.9.3']
      system_wide_defaults: true
